url: http://rettedeinennahverkehr.de
baseurl: ""

# Site settings
title: Rette Deinen Nahverkehr
email: info@okfn.de
description: "Rette deinen Nahverkehr! Offene Fahrplandaten statt vernagelter Systeme"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - CNAME
  - LICENSE