url: https://okfde.github.io
baseurl: ""

# Site settings
title: Rette Deinen Nahverkehr
email: info@okfn.de
description: "Rette deinen Nahverkehr! Offene Fahrplandaten statt vernagelter Systeme"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/okfde

# Postal address (add as many lines as necessary)
address:
  - line: Open Knowledge Foundation Deutschland e.V.
  - line: Singerstr. 109
  - line: 10179 Berlin

# Build settings
markdown: kramdown
permalink: pretty
